// nextwebapp/src/app/_components/LocationInfoRankings.tsx
import React from "react"

export interface LocationInfoWithRank {
  area: string
  areaRank: number
  areaUrl: string
  city: string
  cityRank: number
  cityUrl: string
  overallRank: number
  state: string
  stateRank: number
  stateUrl: string
}

export default function LocationInfoRankings({
  locationInfoWithRank,
}: {
  locationInfoWithRank: LocationInfoWithRank
}) {
  return (
    <div className="text-xs">
      <div>
        <strong>#{locationInfoWithRank.overallRank}</strong>
        <a> Overall</a>
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.stateRank}
          display={locationInfoWithRank.state}
        />
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.areaRank}
          display={locationInfoWithRank.area}
        />
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.cityRank}
          display={locationInfoWithRank.city}
        />
      </div>
    </div>
  )
}

const RankLink = ({ rank, display }: { rank: number; display: string }) => {
  return (
    <>
      <strong>#{rank}</strong> from {display}
      {/* <Link href={`${url}/${link}`} title={display} className="text-success">
        {display}
      </Link> */}
    </>
  )
}

// WebApplication/src/app/_subComponents/location-info-rankings/location-info-rankings.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ComponentBaseWithRoutes } from '../../_common/componentBaseWithRoutes';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  standalone: true,
  selector: 'app-location-info-rankings',
  templateUrl: './location-info-rankings.component.html',
  imports: [CommonModule, RouterModule],
  styleUrls: []
})
export class LocationInfoRankingsComponent extends ComponentBaseWithRoutes implements OnInit {

  @Input('locationInfoWithRank')
  public locationInfoWithRank: any;

  @Input('useEventsNavigation')
  public useEventsNavigation: boolean = false;

  public allRoute!: string;
  public areaRoute!: string;
  public cityRoute!: string;
  public stateRoute!: string;

  ngOnInit() {
    this.allRoute = this.useEventsNavigation ? this.EventsPage : this.AthletesPage
    this.stateRoute = this.useEventsNavigation ? this.EventsStatePage : this.AthletesStatePage
    this.areaRoute = this.useEventsNavigation ? this.EventsAreaPage : this.AthletesAreaPage
    this.cityRoute = this.useEventsNavigation ? this.EventsCityPage : this.AthletesCityPage
  }
}


<div class="font-12">

  <div>
    <strong>#{{locationInfoWithRank.overallRank}}</strong>
    <a class="text-success" [routerLink]="allRoute">
      Overall
    </a>
  </div>

  <ng-container *ngTemplateOutlet="link;context:{rank: locationInfoWithRank.stateRank, display: locationInfoWithRank.state, link: locationInfoWithRank.stateUrl, url: stateRoute}"></ng-container>
  <ng-container *ngTemplateOutlet="link;context:{rank: locationInfoWithRank.areaRank, display: locationInfoWithRank.area, link: locationInfoWithRank.areaUrl, url: areaRoute}"></ng-container>
  <ng-container *ngTemplateOutlet="link;context:{rank: locationInfoWithRank.cityRank, display: locationInfoWithRank.city, link: locationInfoWithRank.cityUrl, url: cityRoute}"></ng-container>

</div>

<ng-template #link let-rank="rank" let-display="display" let-link="link" let-url="url">

  <div class="text-truncate">
    <strong>#{{rank}}</strong> from
    <a class="text-success" [title]="display" [routerLink]="[url, link]">
      {{display}}
    </a>
  </div>

</ng-template>
