// WebApplication/src/app/_subComponents/interval-time/interval-time.component.ts
import { Component, Input } from '@angular/core';
import { PaceWithTime } from '../../_core/paceWithTime';
import { CommonModule } from '@angular/common';

@Component({
  standalone: true,
  selector: 'app-interval-time',
  templateUrl: './interval-time.component.html',
  imports: [CommonModule],
  styleUrls: []
})
export class IntervalTimeComponent {

  @Input('paceTime')
  public paceTime!: PaceWithTime
}


<div *ngIf="paceTime">
  <div class="font-20 font-weight-bold">{{paceTime.timeFormatted}}</div>
  <div *ngIf="paceTime.hasPace">
    <strong class="mr-1">{{paceTime.paceValue || 'N/A'}}</strong>{{paceTime.paceLabel}}
  </div>
</div>
<div *ngIf="!paceTime">--</div>

// nextwebapp/src/app/_components/IntervalTime.tsx
import React from "react"

export interface PaceWithTime {
  timeFormatted: string
  hasPace: boolean
  paceValue: string | null
  paceLabel: string | null
}

export default function IntervalTime({
  paceTime,
}: {
  paceTime: PaceWithTime | null
}) {
  if (!paceTime) {
    return <div>--</div>
  }

  return (
    <div>
      <div className="text-lg font-bold">{paceTime.timeFormatted}</div>
      {paceTime.hasPace && (
        <div>
          <strong className="mr-1">{paceTime.paceValue || "N/A"}</strong>
          {paceTime.paceLabel}
        </div>
      )}
    </div>
  )
}
