// nextwebapp/src/app/_components/LocationInfoRankings.tsx
import React from "react"

export interface LocationInfoWithRank {
  area: string
  areaRank: number
  areaUrl: string
  city: string
  cityRank: number
  cityUrl: string
  overallRank: number
  state: string
  stateRank: number
  stateUrl: string
}

export default function LocationInfoRankings({
  locationInfoWithRank,
}: {
  locationInfoWithRank: LocationInfoWithRank
}) {
  return (
    <div className="text-xs">
      <div>
        <strong>#{locationInfoWithRank.overallRank}</strong>
        <a> Overall</a>
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.stateRank}
          display={locationInfoWithRank.state}
        />
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.areaRank}
          display={locationInfoWithRank.area}
        />
      </div>
      <div>
        <RankLink
          rank={locationInfoWithRank.cityRank}
          display={locationInfoWithRank.city}
        />
      </div>
    </div>
  )
}

const RankLink = ({ rank, display }: { rank: number; display: string }) => {
  return (
    <>
      <strong>#{rank}</strong> from {display}
      {/* <Link href={`${url}/${link}`} title={display} className="text-success">
        {display}
      </Link> */}
    </>
  )
}

// WebApplication/ClientApp/src/app/_subComponents/location-info-rankings/location-info-rankings.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ComponentBaseWithRoutes } from 'src/app/_common/componentBaseWithRoutes';
import { LocationInfoWithRank } from 'src/app/_orchestration/locationInfoWithRank';

@Component({
  selector: 'app-location-info-rankings',
  templateUrl: './location-info-rankings.component.html',
  styleUrls: []
})
export class LocationInfoRankingsComponent extends ComponentBaseWithRoutes implements OnInit, OnChanges {

  @Input('locationInfoWithRank')
  public locationInfoWithRank: LocationInfoWithRank;

  @Input('useEventsNavigation')
  public useEventsNavigation: boolean

  public allRoute: string
  public areaRoute: string
  public cityRoute: string
  public stateRoute: string

  // extract as props to render in template.
  public state: string
  public stateUrl: string
  public area: string
  public areaUrl: string
  public city: string
  public cityUrl: string
  public overallRank: number
  public stateRank: number
  public areaRank: number
  public cityRank: number

  ngOnInit() {
    this.allRoute = this.useEventsNavigation ? this.EventsPage : this.AthletesPage
    this.stateRoute = this.useEventsNavigation ? this.EventsStatePage : this.AthletesStatePage
    this.areaRoute = this.useEventsNavigation ? this.EventsAreaPage : this.AthletesAreaPage
    this.cityRoute = this.useEventsNavigation ? this.EventsCityPage : this.AthletesCityPage
  }

  ngOnChanges(_changes: SimpleChanges): void {
    const {
      state,
      stateUrl,
      area,
      areaUrl,
      city,
      cityUrl,
      overallRank,
      stateRank,
      areaRank,
      cityRank
    } = this.locationInfoWithRank

    this.state = state
    this.stateUrl = stateUrl
    this.area = area
    this.areaUrl = areaUrl
    this.city = city
    this.cityUrl = cityUrl
    this.overallRank = overallRank
    this.stateRank = stateRank
    this.areaRank = areaRank
    this.cityRank = cityRank
  }
}


<div class="font-12">

  <div>
    <strong>#{{overallRank}}</strong>
    <a class="text-success" [routerLink]="allRoute">
      Overall
    </a>
  </div>

  <ng-container *ngTemplateOutlet="link;context:{rank: stateRank, display: state, link: stateUrl, url: stateRoute}"></ng-container>
  <ng-container *ngTemplateOutlet="link;context:{rank: areaRank, display: area, link: areaUrl, url: areaRoute}"></ng-container>
  <ng-container *ngTemplateOutlet="link;context:{rank: cityRank, display: city, link: cityUrl, url: cityRoute}"></ng-container>

</div>

<ng-template #link let-rank="rank" let-display="display" let-link="link" let-url="url">

  <div class="text-truncate">
    <strong>#{{rank}}</strong> from
    <a class="text-success" [title]="display" [routerLink]="[url, link]">
      {{display}}
    </a>
  </div>

</ng-template>
